#!/bin/sh

DAEMON="hss"
DAEMON_ARGS=""
PIDFILE="/var/run/hss.pid"

CONFIG_PATH = /sys/kernel/config
MANUFACTURER="Teknotel Elektronics"
SERIAL="00000000001A"
IDPRODUCT="0x5750"
IDVENDOR="0x0483"  
PRODUCT="Maestro CPX"
CONFIG_NAME="Maestro CPX Config"
MAX_POWER_MA=120
PROTOCOL=0
SUBCLASS=0
REPORT_LENGTH=64
UDC=babasename /sys/class/udc/*

config_usb() {
	printf 'Configuring %s: ' "$UDC"
	mount -t configfs none $CONFIG_PATH
	mkdir $CONFIG_PATH/usb_gadget/custom_gadget
	cd $CONFIG_PATH/usb_gadget/custom_gadget
	mkdir configs/c.1
	mkdir functions/hid.usb0
	echo $PROTOCOL > functions/hid.usb0/protocol
	echo $SUBCLASS > functions/hid.usb0/subclass
	echo $REPORT_LENGTH > functions/hid.usb0/report_length
	echo -ne \\x06\\xff\\x00\\x09\\x01\\xa1\\x01\\x85\\x01\\x09\\x01\\x15\\x00\\x26\\xff\\x00\\x75\\x08\\x95\\x3f\\xb1\\x82\\x85\\x01\\x09\\x01\\x91\\x82\\x85\\x05\\x09\\x05\\x15\\x00\\x26\\xff\\x00\\x75\\x01\\x81\\x82\\x09\\x05\\x75\\x01\\xb1\\x82\\x75\\x07\\x81\\x83\\x85\\x05\\x75\\x07\\xb1\\x83\\xc0 > functions/hid.usb0/report_desc
	mkdir strings/0x409
	mkdir configs/c.1/strings/0x409
	echo $IDPRODUCT > idProduct
	echo $IDVENDOR > idVendor
	echo $SERIAL > strings/0x409/serialnumber
	echo $MANUFACTURER > strings/0x409/manufacturer
	echo $PRODUCT > strings/0x409/product
	echo $CONFIG_NAME > configs/c.1/strings/0x409/configuration
	echo $MAX_POWER_MA > configs/c.1/MaxPower
	ln -s functions/hid.usb0 configs/c.1
	echo $UDC > UDC
}

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "/usr/local/cpx/bin/$DAEMON" -- $DAEMON_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop () {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart () {
	stop
	sleep 1
	start
}

case "$1" in
        start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac